export enum ValidInstanceState {
  Running = 'running',
  Pending = 'pending',
  Stopped = 'stopped',
  Stopping = 'stopping',
  ShuttingDown = 'shutting-down',
  Terminated = 'terminated',
}
export enum AlarmClassification {
  Critical = 'Critical',
  Warning = 'Warning',
}

export enum ValidDBInstanceState {
  Available = 'available',
  BackingUp = 'backing-up',
  Creating = 'creating',
  Deleting = 'deleting',
  Failed = 'failed',
  Modifying = 'modifying',
  Rebooting = 'rebooting',
  Renaming = 'renaming',
  ResettingMasterCredentials = 'resetting-master-credentials',
  RestoreError = 'restore-error',
  StorageFull = 'storage-full',
  Upgrading = 'upgrading',
  configuringEnhancedMonitoring = 'configuring-enhanced-monitoring',
  configuringIAMDatabaseAuthentication = 'configuring-iam-database-auth',
  configuringLogExports = 'configuring-log-exports',
  convertingToVpc = 'converting-to-vpc',
  DeletePreCheck = 'delete-precheck',
  inaccessibleEncryptionCredentials = 'inaccessible-encryption-credentials',
  inaccessibleEncryptionCredentialsRecoverable = 'inaccessible-encryption-credentials-recoverable',
  incompatibleNetwork = 'incompatible-network',
  incompatibleOptionGroup = 'incompatible-option-group',
  incompatibleParameters = 'incompatible-parameters',
  insufficientCapacity = 'insufficient-capacity',
  Maintenance = 'maintenance',
  MovingToVpc = 'moving-to-vpc',
  Starting = 'starting',
  Stopped = 'stopped',
  storageConfigUpgrade = 'storage-config-upgrade',
  StorageOptimization = 'storage-optimization',
}
