/**
 * @fileoverview RDS_CLUSTER alarm configuration definitions.
 *
 * This file contains the default configurations for all supported RDS_CLUSTER CloudWatch alarms managed by AutoAlarm.
 *
 * @requires
 * - Approval from Owners Team lead and consultation before adding new alarms
 * - Anomaly Alarms can only use the following comparison operators: GreaterThanUpperThreshold, LessThanLowerOrGreaterThanUpperThreshold, LessThanLowerThreshold
 *
 * @Owners DB WARDEN/HARMONY (Prometheus engineering resource)
 */

import {MetricAlarmConfig} from '../types/index.mjs';

export const PROMETHEUS_ORACLEDB_CONFIGS: MetricAlarmConfig[] = [
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      queryPattern:
        '_STATISTIC(oracledb_activity_execute_count > _THRESHOLD[_PERIOD]) ',
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_execute_count',
    metricName: 'oracledb_activity_execute_count',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_parse_count_total',
    metricName: 'oracledb_activity_parse_count_total',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
  {
    tagKey: 'activity_user_commits',
    metricName: 'oracledb_activity_user_commits',
    metricNamespace: 'oracledb',
    defaultCreate: true,
    anomaly: null,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 4,
      period: 60,
      evaluationPeriods: null,
      statistic: null,
      dataPointsToAlarm: null,
      comparisonOperator: null,
      missingDataTreatment: null,
    },
  },
] as const;
