// THIS FILE WAS AUTOGENERATED VIA ./_template-configs.mts
// See file for instructions on how to generate new alarm config files.
/**
 * @fileoverview RDS_CLUSTER alarm configuration definitions.
 *
 * This file contains the default configurations for all supported RDS_CLUSTER CloudWatch alarms managed by AutoAlarm.
 *
 * ---
 *
 * @usage
 * The MetricAlarm interface {@link MetricAlarmConfig} contained in this list are strongly typed, specifically in the defaults object for
 *  * statistic
 *  * comparisonOperator
 *  * missingDataTreatment
 *
 *  It is strongly encouraged to use the following utilities/enums to populate values for the following fields which
 *  provide thorough TSDOC and autocomplete. However, you may also use string literals:
 *   * `comparisonOperator` - Use the AWS SDK enums for comparison operators {@link ComparisonOperator}
 *   * `missingDataTreatment` - Use the AWS SDK enums for missing data treatment {@link TreatMissingData}
 *
 * These are demonstrated in the examples below.
 *
 * ---
 *
 * @instructions
 * ### Adding to a current alarm configuration in this file
 * 1. Create a new alarm config file if it does not exist by running in the project root the following:
      `pnpm create-cw-configs [serviceName] [Team name that owns the Alarms]`
 * 2. Add the new configuration to the RDS_CLUSTER array
 * 3. Ensure the `tagKey` follows the tag key naming conventions in the README. Does not include 'autoalarm' (e.g. 5xx-count-anomaly)
 * 4. Set appropriate default values for all required fields
 * 5. Use the AWS SDK enums for comparison operators {@link ComparisonOperator} and missing data treatment {@link TreatMissingData}
 *
 * ---
 *
 * @requires
 * - Approval from Owners Team lead and consultation before adding new alarms
 * - Anomaly Alarms can only use the following comparison operators: GreaterThanUpperThreshold, LessThanLowerOrGreaterThanUpperThreshold, LessThanLowerThreshold
 *
 * ---
 *
 * @example
 * ```typescript
 * // Adding a new EC2 alarm configuration to configs file
 * export const _EC2Configs: MetricAlarmConfig[] = [ // only create the configs array if it does not exist
 *                                                             // Otherwise add to the existing array following the
 *                                                             // pattern below
 * {
 *   tagKey: 'new-metric-alarm',                          // Unique identifier
 *   metricName: 'MetricName',                            // CloudWatch metric name
 *   metricNamespace: 'AWS/EC2',
 *   defaultCreate: false,                                // Whether to create by default
 *   anomaly: false,                                      // Whether this is anomaly detection
 *   defaults: {
 *     warningThreshold: 100,                             // Warning threshold (null if not used)
 *     criticalThreshold: 200,                            // Critical threshold (null if not used)
 *     period: 60,                                        // Period in seconds
 *     evaluationPeriods: 2,                              // Evaluation periods
 *     statistic: 'Average',                                  // Statistic to use
 *     dataPointsToAlarm: 2,                              // Data points required to alarm
 *     comparisonOperator: ComparisonOperator.GREATER_THAN_THRESHOLD, // Comparison operator
 *     missingDataTreatment: TreatMissingData.IGNORE,                    // How to treat missing data
 *   },
 * },
 * ---
 *
 * @Owners DB WARDEN
 */

import {MetricAlarmConfig} from '#types/alarm-config-types.mjs';
import {ComparisonOperator} from '@aws-sdk/client-cloudwatch';
import {TreatMissingData} from 'aws-cdk-lib/aws-cloudwatch';

/**
 * _RDS_CLUSTER alarm configuration definitions.
 * Implements the {@link MetricAlarmConfig} interface.
 * Used to map a tag key to a CloudWatch metric name and namespace to default alarm configurations {@link MetricAlarmOptions}.
 */
export const _RDS_CLUSTER: MetricAlarmConfig[] = [
  // 1) CPU - Static Only
  {
    tagKey: 'cpu',
    metricName: 'CPUUtilization',
    metricNamespace: 'AWS/RDS',
    defaultCreate: false,
    anomaly: false,
    defaults: {
      warningThreshold: 90,
      criticalThreshold: 95,
      period: 600,
      evaluationPeriods: 1,
      statistic: 'Maximum',
      dataPointsToAlarm: 1,
      comparisonOperator: ComparisonOperator.GreaterThanThreshold,
      missingDataTreatment: TreatMissingData.IGNORE,
    },
  },

  // 2) DatabaseConnections - Anomaly

  {
    tagKey: 'db-connections-anomaly',
    metricName: 'DatabaseConnections',
    metricNamespace: 'AWS/RDS',
    defaultCreate: true,
    anomaly: true,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 5,
      period: 600,
      evaluationPeriods: 5,
      statistic: 'Average',
      dataPointsToAlarm: 5,
      comparisonOperator: 'GreaterThanUpperThreshold',
      missingDataTreatment: 'ignore',
    },
  },

  // 3) DBLoad - Anomaly Only
  {
    tagKey: 'dbload-anomaly',
    metricName: 'DBLoad',
    metricNamespace: 'AWS/RDS',
    defaultCreate: true,
    anomaly: true,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 5,
      period: 300,
      evaluationPeriods: 1,
      statistic: 'Maximum',
      dataPointsToAlarm: 1,
      comparisonOperator: 'GreaterThanUpperThreshold',
      missingDataTreatment: 'ignore',
    },
  },

  // 4) Deadlocks - Static
  {
    tagKey: 'deadlocks',
    metricName: 'Deadlocks',
    metricNamespace: 'AWS/RDS',
    defaultCreate: true,
    anomaly: false,
    defaults: {
      warningThreshold: 0,
      criticalThreshold: 0,
      period: 120,
      evaluationPeriods: 1,
      statistic: 'Sum',
      dataPointsToAlarm: 1,
      comparisonOperator: 'GreaterThanThreshold',
      missingDataTreatment: 'ignore',
    },
  },

  // 5) FreeableMemory - Static Only
  {
    tagKey: 'freeable-memory',
    metricName: 'FreeableMemory',
    metricNamespace: 'AWS/RDS',
    defaultCreate: true,
    anomaly: false,
    defaults: {
      warningThreshold: 2000000000,
      criticalThreshold: 100000000,
      period: 120,
      evaluationPeriods: 2,
      statistic: 'Maximum',
      dataPointsToAlarm: 2,
      comparisonOperator: 'LessThanThreshold',
      missingDataTreatment: 'ignore',
    },
  },

  // 7) ReplicaLag - Static + Anomaly
  {
    tagKey: 'replica-lag',
    metricName: 'ReplicaLag',
    metricNamespace: 'AWS/RDS',
    defaultCreate: true,
    anomaly: false,
    defaults: {
      warningThreshold: 60,
      criticalThreshold: 300,
      period: 120,
      evaluationPeriods: 1,
      statistic: 'Maximum',
      dataPointsToAlarm: 1,
      comparisonOperator: 'GreaterThanThreshold',
      missingDataTreatment: 'ignore',
    },
  },
  {
    tagKey: 'replica-lag-anomaly',
    metricName: 'ReplicaLag',
    metricNamespace: 'AWS/RDS',
    defaultCreate: true,
    anomaly: true,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 5,
      period: 120,
      evaluationPeriods: 1,
      statistic: 'Average',
      dataPointsToAlarm: 1,
      comparisonOperator: 'GreaterThanUpperThreshold',
      missingDataTreatment: 'ignore',
    },
  },

  // 8) SwapUsage - Anomaly Only
  {
    tagKey: 'swap-usage-anomaly',
    metricName: 'SwapUsage',
    metricNamespace: 'AWS/RDS',
    defaultCreate: true,
    anomaly: true,
    defaults: {
      warningThreshold: 2,
      criticalThreshold: 5,
      period: 120,
      evaluationPeriods: 1,
      statistic: 'Maximum',
      dataPointsToAlarm: 1,
      comparisonOperator: 'GreaterThanUpperThreshold',
      missingDataTreatment: 'ignore',
    },
  },

  // 9) WriteLatency - Anomaly

  {
    tagKey: 'write-latency-anomaly',
    metricName: 'WriteLatency',
    metricNamespace: 'AWS/RDS',
    defaultCreate: true,
    anomaly: true,
    defaults: {
      warningThreshold: 5,
      criticalThreshold: 9,
      period: 300,
      evaluationPeriods: 2,
      statistic: 'Average',
      dataPointsToAlarm: 2,
      comparisonOperator: 'GreaterThanUpperThreshold',
      missingDataTreatment: 'ignore',
    },
  },
  // add more as needed
];
